export default [
    /^https\:\/\/maps\.apple\.com\/(?:\?.*&|\?)(?:q|ll)=(-?\d+(?:\.\d+)),(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^https\:\/\/www\.openstreetmap\.org\/(?:\?.*&|\?)mlat=(-?\d+(?:\.\d+))(?:&.*)?&mlon=(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^geo:(-?\d+(?:\.\d+)),(-?\d+(?:\.\d+))/,

    /^https\:\/\/tools\.wmflabs\.org\/geohack\/geohack\.php(?:\?.*&|\?)params=(-?\d+(?:\.\d+))_N_(-?\d+(?:\.\d+))_W_.*(?:&.*|$)/,
    /^https\:\/\/mapper\.acme\.com\/(?:\?.*&|\?)ll=(-?\d+(?:\.\d+)),(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^http\:\/\/www\.arctic\.io\/wikipedia\/(?:\?.*&|\?)lon=(-?\d+(?:\.\d+))(?:&.*)?&lat=(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^https\:\/\/www\.bing\.com\/maps\/(?:\?.*&|\?)cp=(-?\d+(?:\.\d+))~(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^https\:\/\/blue-marble\.de\/(?:\?.*&|\?)lon=(-?\d+(?:\.\d+))(?:&.*)?&nlat=(-?\d+(?:\.\d+))(?:&.*|$)/,
    [/^https\:\/\/copernix\.io\/#(?:\?.*&|\?)where=(-?\d+(?:\.\d+)),(-?\d+(?:\.\d+)),\d+(?:&.*|$)/, 2, 1],
    /^https\:\/\/www\.fourmilab\.ch\/cgi-bin\/uncgi\/Earth(?:\?.*&|\?)lat=(-?\d+(?:\.\d+))(?:&.*)&lon=(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^http\:\/\/www\.geabios\.com\/html\/services\/maps\/PublicMap\.htm(?:\?.*&|\?)lat=(-?\d+(?:\.\d+))(?:&.*)?&lon=(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^http\:\/\/www\.geonames\.org\/maps\/google_(-?\d+(?:\.\d+))_(-?\d+(?:\.\d+))\.html$/,
    /^https\:\/\/maps\.google\.com\/maps(?:\?.*&|\?)(?:q|ll)=(-?\d+(?:\.\d+)),(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^http\:\/\/www\.gpsvisualizer\.com\/map_input(?:\?.*&|\?)form:data=name,latitude,longitude%0D%22(?:[a-zA-Z\s]+)%22,(-?\d+(?:\.\d+)),(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^https\:\/\/wego\.here\.com\/location\/(?:\?.*&|\?)map=(-?\d+(?:\.\d+)),(-?\d+(?:\.\d+)),\d+,normal(?:&.*|$)/,
    /^https\:\/\/www\.mapquest\.com\/latlng\/(-?\d+(?:\.\d+)),(-?\d+(?:\.\d+))(?:\?.*|$)/,
    /^worldwind\:\/\/goto\/(?:.*&)?lat=(-?\d+(?:\.\d+))(?:&.*)?&lon=(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^https\:\/\/www\.terraserver\.com\/view(?:\?.*&|\?)lat=(-?\d+(?:\.\d+))(?:&.*)?&lng=(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^https\:\/\/www\.waze\.com\/livemap\/(?:\?.*&|\?)lat=(-?\d+(?:\.\d+))(?:&.*)?&lon=(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^http\:\/\/wikimapia\.org\/(?:#.*&|#)lat=(-?\d+(?:\.\d+))(?:&.*)?&lon=(-?\d+(?:\.\d+))(?:&.*|$)/,
    /^https\:\/\/wma\.wmflabs\.org\/iframe\.html(?:\?.*&|\?)wma=(-?\d+(?:\.\d+))_(-?\d+(?:\.\d+))_\d+_\d+_[a-z]+_\d+_[a-z]+(?:&.*|$)/,
    [/^https\:\/\/maps\.yandex\.com\/(?:\?.*&|\?)(?:ll|pt)=(-?\d+(?:\.\d+)),(-?\d+(?:\.\d+))(?:&.*|$)/, 2, 1],
    /^https\:\/\/zoom\.earth\/(?:\?.*&|\?)lat=(-?\d+(?:\.\d+))(?:&.*)?&lon=(-?\d+(?:\.\d+))(?:&.*|$)/,
];
